apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pqcjok2gj-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pqcjok2gj-go 
  name: pqcjok2gj-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pqcjok2gj-go 
